name: Build documentation

on:
  pull_request:
    branches:
      - main
      - initial

jobs:
  doc-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox

    - name: Run Tox for Documentation
      run: tox -e docs
