name: Manual Package

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: envars
        run: env

      # - name: Test output 1
      #   run: cat /home/runner/.m2/settings.xml

      # - name: maven-settings-xml-action
      #   # https://github.com/marketplace/actions/generate-settings-xml-for-maven-builds
      #   uses: whelk-io/maven-settings-xml-action@v22
      #   with:
      #     servers: | 
      #       [{
      #          "id": "github",
      #          "username": "${env.GITHUB_ACTOR}",
      #          "password": "${env.GITHUB_TOKEN}"

      #       }]
      #     repositories: |
      #       [{ 
      #          "id": "github",
      #          "url": "https://maven.pkg.github.com/${env.GITHUB_REPOSITORY}"  
      #       }]
      #     profiles: |
      #       [{
      #          "id": "github",
      #          "properties": { 
      #              "altSnapshotDeploymentRepository": "github::https://maven.pkg.github.com/${env.GITHUB_REPOSITORY}",
      #              "altReleaseDeploymentRepository": "github::https://maven.pkg.github.com/${env.GITHUB_REPOSITORY}"
      #           }
      #       }]

      - name: Test output 2
        run: echo "github::https://maven.pkg.github.com/${env.GITHUB_REPOSITORY}"

      - name: Build with Maven
        run: mvn -B deploy --file pom.xml -DaltDeploymentRepository="github::https://maven.pkg.github.com/${env.GITHUB_REPOSITORY}"
