name: Manual Package

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'

      - uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: false

      - name: Test output
        run: cat /home/runner/.m2/settings.xml

      - name: Build with Maven
        run: mvn -B package --file pom.xml
        