name: Manual Package

on:
  workflow_dispatch:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: Test output 1
        run: cat /home/runner/.m2/settings.xml

      - uses: s4u/maven-settings-action@v3.1.0
        with:
          githubServer: true
          profiles: |
            [{
               "id": "github",
               "properties": { 
                   "altSnapshotDeploymentRepository": "github_harald::https://maven.pkg.github.com/harald-tsys/opentelekomcloud-functiongraph-java",
                   "altReleaseDeploymentRepository": "github_harald::https://maven.pkg.github.com/harald-tsys/opentelekomcloud-functiongraph-java"
                }
            }]

      - name: Test output 2
        run: cat /home/runner/.m2/settings.xml

      # - name: Build with Maven
      #   run: mvn -B package --file pom.xml
