name: release
# This workflow is triggered when publishing a new GitHub release
on:
  # release:
  #   types:
  #     - published

  # pull_request:
  workflow_dispatch:
    inputs:
      version: 
        type: string
        description: Release version vx.y.z-alpha
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
          server-id: github

      - name: Setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.6.3

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: configure version
        id: config_version
        run: |
          echo "branch: ${{ github.ref_name }}"
          echo "commit-sha: ${{ github.sha }}"
          echo "repository: ${{ github.repository }}"

          echo "organization name: ${{ github.repository_owner }}"
          echo "repository name: ${{ github.event.repository.name }}"
          
          echo "JAVA_POM_VERSION=$(echo ${{ github.event.inputs.version }} | cut -d'v' -f2)" >> "$GITHUB_ENV"
          echo "java_pom_version=$(echo ${{ github.event.inputs.version }} | cut -d'v' -f2)" >> "$GITHUB_OUTPUT"

      - name: set new version in pom
        id: set_pom_version
        run: |
          echo "new pom version: $JAVA_POM_VERSION"
          mvn versions:set -DnewVersion=$JAVA_POM_VERSION
 
      - name: deploy artifacts to github artifactory
        id: deploy_github
        run: | 
          mvn -B deploy --file pom.xml \
            -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: create release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: false


      # - name: Maven prepare release
      #   run: |
      #       mvn --batch-mode \
      #         org.apache.maven.plugins:maven-release-plugin:3.1.1:prepare \
      #        -Dtag=${{ github.event.release.tag_name }} \ 
      #        -DautoVersionSubmodules=true \
      #        -DdevelopmentVersion=0.0.1-SNAPSHOT \
      #        -DreleaseVersion=${{ github.event.inputs.version }}
                          
      #   env:
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - name: display
      #   run: |
      #     cat release.properties     

      # - name: Maven perform release
      #   run: |
      #       mvn --batch-mode \
      #         org.apache.maven.plugins:maven-release-plugin:3.1.1:perform \
      #        -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}"
             
      #   env:
      #      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





      

