name: release
# This workflow is triggered when publishing a new GitHub release
on:
  release:
    types:
      - published

  pull_request:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - id: get-pom-version
        name: Get Pom Version
        uses: jactions/maven-version@v1

      - name: echo
        run: |
          echo "POM version: ${{ steps.get-pom-version.outputs.version }}"
          echo "branch: ${{ github.ref_name }}"
          echo "commit-sha: ${{ github.sha }}"
          echo "organization: ${{ github.repository_owner }}"
          echo "repository: ${{ github.event.repository.name }}"
          echo "version: ${{ github.event.release.tag_name }}"

