name: release
# This workflow is triggered when publishing a new GitHub release
on:
  # release:
  #   types:
  #     - published

  # pull_request:
  workflow_dispatch:
    inputs:
      version: 
        type: string
        description: Release version vx.y.z-alpha
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkou project
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
          server-id: github

      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: echo
        run: |
          echo "branch: ${{ github.ref_name }}"
          echo "commit-sha: ${{ github.sha }}"
          echo "repository: ${{ github.event.repository }}"
          echo "organization name: ${{ github.repository_owner }}"
          echo "repository name: ${{ github.event.repository.name }}"
          echo "version: ${{ github.event.release.tag_name }}"
           
          echo "JAVA_POM_VERSION=$(echo ${{ github.event.release.tag_name }} | cut -d'v' -f2)" >> "$GITHUB_ENV"

      # - name: create new release
      #   run: |
      #     echo "new pom version: ${JAVA_POM_VERSION}"

      #     mvn versions:set -DnewVersion=$JAVA_POM_VERSION
 
      #     mvn -B deploy --file pom.xml \
      #       -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository }}"
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven prepare release
        run: |
            mvn --batch-mode \
             -Dtag=${{ github.event.release.tag_name }} \
              release:prepare \
             -DautoVersionSubmodules=true \
             -DdevelopmentVersion=0.0.1-SNAPSHOT \
             -DreleaseVersion=${{ github.event.inputs.version }} \
             -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}"
                          
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: display
        run: |
          cat release.properties     

      - name: Maven perform release
        run: |
            mvn --batch-mode \
              release:perform \
             -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository_owner }}/${{ github.repository_name }}"
             
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}





      

