name: release2
# This workflow is triggered when publishing a new GitHub release

on: 
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup java
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"
          server-id: github

      - name: Setup maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.6.3

      - name: configure-git-user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"

      - name: get-pom-version
        id: pom-version
        run: |
          echo "JAVA_POM_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> "$GITHUB_OUTPUT"

      - name: print-pom-version    
        run: echo "JAVA_POM_VERSION=${{ steps.pom-version.outputs.JAVA_POM_VERSION }}"

      # - name: cat-settings.xml
      #   run: |
      #     cat ~/.m2/settings.xml

      # - name: config-settings
      #   uses: s4u/maven-settings-action@v3.1.0
      #   with:
      #     repositories: '[{"id":"github","name":"github","url":"https://maven.pkg.github.com/${{ github.repository }}","snapshots":{"enabled":true}}]'

      - name: deploy-artifacts-to-github
        id: deploy_github
        run: | 
          mvn -B deploy --file pom.xml \
            -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # https://github.com/ncipollo/release-action/blob/main/.github/workflows/release.yml
      # - name: Create Release
      # # https://github.com/ncipollo/release-action/blob/main/.github/workflows/release.yml
      #   id: create_release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     allowUpdates: true
      #     draft: true
      #     generateReleaseNotes: true
