name: release
# This workflow is triggered when publishing a new GitHub release
on:
  release:
    types:
      - published

  # pull_request:
  # workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "21"
          cache: "maven"

      - name: echo
        run: |
          echo "branch: ${{ github.ref_name }}"
          echo "commit-sha: ${{ github.sha }}"
          echo "organization: ${{ github.repository_owner }}"
          echo "repository: ${{ github.event.repository.name }}"
          echo "version: ${{ github.event.release.tag_name }}"
           
          echo "JAVA_POM_VERSION=$(echo ${{ github.event.release.tag_name }} | cut -d'v' -f2)" >> "$GITHUB_ENV"

      - name: create new release
        run: |
          echo "new pom version: ${JAVA_POM_VERSION}"

          mvn versions:set -DnewVersion=$JAVA_POM_VERSION
 
          mvn -B deploy --file pom.xml \
            -DaltDeploymentRepository="github::https://maven.pkg.github.com/${{ github.repository }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



      

